spring:
  application:
    name: first-service
server:
  port: 8081
  address: 0.0.0.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    register-with-eureka: true
    fetch-registry: true